name: sample
description: A Dart project.
version: 1.0.0

environment:
  sdk: '^3.4.0-190.1.beta'

dependencies:
  ffi: ^1.1.2
  dart_native: ^0.2.6

dev_dependencies:
  build_runner: ^2.1.4
  dart_native_gen: ^0.2.6